/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/radiocomp.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[-0.47, 1.41, -0.64]} scale={[0.27, 1.11, 0.59]}>
        <mesh geometry={nodes.Cube_1.geometry} material={materials.Material} />
        <mesh geometry={nodes.Cube_2.geometry} material={nodes.Cube_2.material} />
        <group position={[0.07, 1, 0.65]} scale={[2.76, 0.66, 1.24]}>
          <mesh geometry={nodes.Circle001.geometry} material={nodes.Circle001.material} />
          <mesh geometry={nodes.Circle001_1.geometry} material={nodes.Circle001_1.material} />
          <mesh geometry={nodes.Circle001_2.geometry} material={nodes.Circle001_2.material} />
        </group>
        <group position={[0.07, 1, -0.62]} scale={[2.76, 0.66, 1.24]}>
          <mesh geometry={nodes.Circle002.geometry} material={nodes.Circle002.material} />
          <mesh geometry={nodes.Circle002_1.geometry} material={nodes.Circle002_1.material} />
          <mesh geometry={nodes.Circle002_2.geometry} material={nodes.Circle002_2.material} />
        </group>
        <mesh
          geometry={nodes.bool_obj.geometry}
          material={nodes.bool_obj.material}
          position={[0.01, 0.52, -1]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
        />
        <mesh
          geometry={nodes.bool_obj001.geometry}
          material={nodes.bool_obj001.material}
          position={[0.02, 0.53, -1.04]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
        />
        <mesh
          geometry={nodes.bool_obj002.geometry}
          material={materials['default']}
          position={[-0.01, 0.54, -0.95]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
        />
        <mesh
          geometry={nodes.bool_obj003.geometry}
          material={nodes.bool_obj003.material}
          position={[0.01, 0.79, -1.04]}
          rotation={[1.57, 0, -Math.PI]}
        />
        <mesh
          geometry={nodes.bool_obj004.geometry}
          material={nodes.bool_obj004.material}
          position={[-0.02, 0.27, -1.04]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
        />
        <mesh
          geometry={nodes.bool_obj005.geometry}
          material={nodes.bool_obj005.material}
          position={[1, 0.28, 0.01]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.bool_obj006.geometry}
          material={nodes.bool_obj006.material}
          position={[0.02, 0.87, -1]}
          rotation={[1.66, 0, -Math.PI]}
          scale={[3.74, 1.69, 0.91]}
        />
        <mesh
          geometry={nodes.Cylinder.geometry}
          material={nodes.Cylinder.material}
          position={[0.05, 2.6, -0.64]}
          scale={[1.23, 0.58, 0.55]}
        />
        <mesh
          geometry={nodes.Cylinder001.geometry}
          material={nodes.Cylinder001.material}
          position={[0.02, 2.62, 0.64]}
          scale={[1.23, 0.58, 0.55]}
        />
        <mesh
          geometry={nodes.Cylinder002.geometry}
          material={nodes.Cylinder002.material}
          position={[0.03, 1.11, -0.16]}
          scale={[-0.99, -0.24, -0.44]}>
          <mesh
            geometry={nodes.Nut.geometry}
            material={materials['CC0Textures/Metal012/1K-JPG.001']}
            position={[0.05, 0.34, 0.01]}
            scale={[0.09, 0.09, 0.09]}
          />
        </mesh>
        <group position={[0.02, 1.03, 0.22]} scale={[0.77, 0.14, 0.35]}>
          <mesh geometry={nodes.Cylinder001_1.geometry} material={nodes.Cylinder001_1.material} />
          <mesh geometry={nodes.Cylinder001_2.geometry} material={materials['Material.002']} />
        </group>
        <mesh
          geometry={nodes.Examples_033.geometry}
          material={nodes.Examples_033.material}
          position={[-0.04, 0.27, -1.13]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[1.25, 0.45, 0.33]}
        />
        <mesh
          geometry={nodes.Examples_033001.geometry}
          material={nodes.Examples_033001.material}
          position={[-0.01, 0.79, -1.12]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[1.25, 0.45, 0.33]}
        />
        <mesh
          geometry={nodes.Text.geometry}
          material={materials['CC0Textures/Metal029/1K-JPG']}
          position={[0.96, -0.34, -0.02]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          scale={[0.28, 0.63, 0.15]}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/radiocomp.glb')
